import {
  FIREBASE_API_KEY,
  FIREBASE_APP_ID,
  FIREBASE_CLIENT_ID,
  FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET,
} from "@env";
export default {
  FIREBASE_CLIENT_ID,
  FIREBASE_APP_ID,
  FIREBASE_API_KEY,
  FIREBASE_STORAGE_BUCKET,
  FIREBASE_PROJECT_ID,
};
